# マウス移動
int16 mouse_delta_x   # マウスX軸移動量 (相対値)
int16 mouse_delta_y   # マウスY軸移動量 (相対値)

# マウスボタン
bool mouse_left_button   # マウス左ボタン状態
bool mouse_right_button  # マウス右ボタン状態
bool mouse_wheel_button  # マウスホイールボタン状態
bool mouse_side_1_button # マウスサイド1ボタン状態
bool mouse_side_2_button # マウスサイド2ボタン状態

# キーボード - 数字キー
bool key_1   # 1キー状態
bool key_2   # 2キー状態
bool key_3   # 3キー状態
bool key_4   # 4キー状態
bool key_5   # 5キー状態

# キーボード - 上段
bool key_tab # Tabキー状態
bool key_q   # Qキー状態
bool key_w   # Wキー状態
bool key_e   # Eキー状態
bool key_r   # Rキー状態
bool key_t   # Tキー状態

# キーボード - 中段
bool key_a   # Aキー状態
bool key_s   # Sキー状態
bool key_d   # Dキー状態
bool key_f   # Fキー状態
bool key_g   # Gキー状態
bool key_h   # Hキー状態

# キーボード - 下段
bool key_shift # Shiftキー状態
bool key_z     # Zキー状態
bool key_x     # Xキー状態
bool key_c     # Cキー状態
bool key_v     # Vキー状態
bool key_b     # Bキー状態

# 修飾キー・その他
bool key_ctrl   # Ctrlキー状態
bool key_alt    # Altキー状態
bool key_space  # Spaceキー状態
bool key_enter  # Enterキー状態
